server:
  port: 8091

spring:
  application:
    name: provider
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/springcloud-demo?allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml # MyBatis Mapper 所对应的 XML 文件位置
  type-aliases-package: com.fancyliu.springcloud.demo.provider.model